# Generated by Django 4.2.7 on 2023-11-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_toda_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='DailyTask',
        ),
    ]
